//
// DelayAPOInterface.idl -- Copyright (c) Microsoft Corporation. All rights reserved.
//
// Description:
//
//      The interface and type definitions for Delay APO functionality.
//
import "oaidl.idl";
import "ocidl.idl";
import "audioenginebaseapo.idl";

[
    object,
    uuid(2EC9DB25-0234-4991-8533-B2EFC6C8D6C9),
    pointer_default(unique)
]
interface IDelayAPOMFX : IUnknown
{
};

[
    object,
    uuid(2EC9DE1E-955E-4FB9-BC6A-8CC8944AB9D2),
    pointer_default(unique)
]
interface IDelayAPOSFX : IUnknown
{
};

