//
// AudioInjectorAPODll.idl -- Copyright (c) 2025 Maxim [maxirmx] Samsonov. All rights reserved.
//
// Author:
//
// Description:
//
// AudioInjectorAPODll.idl : Definition of COM interfaces and coclasses for the DLL.

import "oaidl.idl";
import "ocidl.idl";
import "AudioInjectorAPOInterface.idl";

//-------------------------------------------------------------------------
// AudioInjectorAPODlllib
//
[
    uuid(2EC96EC6-EF8C-4BFF-8C73-D890264EFA93),
    version(1.0)
]
library AudioInjectorAPODlllib
{
    importlib("stdole2.tlb");

    // for Delay APO - MFX
    [
        uuid(2EC9CC40-C59F-4E45-A7AD-17138B56B422)
    ]
    coclass AudioInjectorAPOMFX
    {
        interface IAudioProcessingObject;
        interface IAudioProcessingObjectRT;
        interface IAudioProcessingObjectConfiguration;
        interface IMMNotificationClient;
        interface IAudioSystemEffects;
        [default] interface IAudioInjectorAPOMFX;
    };

    // for Delay APO - SFX
    [
        uuid(2EC95D17-DF3D-48D2-8433-AB0D9929AABF)
    ]
    coclass AudioInjectorAPOSFX
    {
        interface IAudioProcessingObject;
        interface IAudioProcessingObjectRT;
        interface IAudioProcessingObjectConfiguration;
        interface IMMNotificationClient;
        interface IAudioSystemEffects;
        [default] interface IAudioInjectorAPOSFX;
    };


}
